ALTER TABLE "automation_definition" DROP CONSTRAINT "automation_definition_trigger_valid";--> statement-breakpoint
ALTER TABLE "automation_definition" DROP CONSTRAINT "automation_definition_recurrence_consistent";--> statement-breakpoint
ALTER TABLE "automation_run" DROP CONSTRAINT "automation_run_trigger_valid";--> statement-breakpoint
ALTER TABLE "automation_run" DROP CONSTRAINT "automation_run_schedule_matches_trigger";--> statement-breakpoint
ALTER TABLE "automation_definition" ADD COLUMN "condition_resource_id" uuid;--> statement-breakpoint
ALTER TABLE "automation_definition" ADD COLUMN "condition_threshold_percent" integer;--> statement-breakpoint
ALTER TABLE "automation_run" ADD COLUMN "source_metric_sample_id" uuid;--> statement-breakpoint
ALTER TABLE "automation_definition" ADD CONSTRAINT "automation_definition_condition_resource_id_resource_id_fk" FOREIGN KEY ("condition_resource_id") REFERENCES "public"."resource"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "automation_run" ADD CONSTRAINT "automation_run_source_metric_sample_id_metric_sample_id_fk" FOREIGN KEY ("source_metric_sample_id") REFERENCES "public"."metric_sample"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "automation_definition_condition_idx" ON "automation_definition" USING btree ("project_id","condition_resource_id","enabled");--> statement-breakpoint
ALTER TABLE "automation_definition" ADD CONSTRAINT "automation_definition_trigger_valid" CHECK ("automation_definition"."trigger_type" in ('on_creation_once', 'recurring_interval', 'synthetic_event', 'synthetic_condition'));--> statement-breakpoint
ALTER TABLE "automation_definition" ADD CONSTRAINT "automation_definition_recurrence_consistent" CHECK (("automation_definition"."trigger_type" = 'on_creation_once' and "automation_definition"."event_type" is null and "automation_definition"."condition_resource_id" is null and "automation_definition"."condition_threshold_percent" is null and "automation_definition"."recurrence_start_at" is null and "automation_definition"."recurrence_every_minutes" is null and "automation_definition"."next_occurrence_at" is null) or ("automation_definition"."trigger_type" = 'recurring_interval' and "automation_definition"."event_type" is null and "automation_definition"."condition_resource_id" is null and "automation_definition"."condition_threshold_percent" is null and "automation_definition"."recurrence_start_at" is not null and "automation_definition"."recurrence_every_minutes" between 5 and 10080 and "automation_definition"."next_occurrence_at" is not null) or ("automation_definition"."trigger_type" = 'synthetic_event' and "automation_definition"."event_type" in ('git.pull_request.merged', 'monitor.down', 'monitor.recovered') and "automation_definition"."condition_resource_id" is null and "automation_definition"."condition_threshold_percent" is null and "automation_definition"."recurrence_start_at" is null and "automation_definition"."recurrence_every_minutes" is null and "automation_definition"."next_occurrence_at" is null) or ("automation_definition"."trigger_type" = 'synthetic_condition' and "automation_definition"."event_type" is null and "automation_definition"."condition_resource_id" is not null and "automation_definition"."condition_threshold_percent" between 0 and 99 and "automation_definition"."recurrence_start_at" is null and "automation_definition"."recurrence_every_minutes" is null and "automation_definition"."next_occurrence_at" is null));--> statement-breakpoint
ALTER TABLE "automation_run" ADD CONSTRAINT "automation_run_trigger_valid" CHECK ("automation_run"."trigger" in ('on_creation', 'manual', 'scheduled', 'recurring', 'synthetic_event', 'synthetic_condition'));--> statement-breakpoint
ALTER TABLE "automation_run" ADD CONSTRAINT "automation_run_schedule_matches_trigger" CHECK (("automation_run"."trigger" in ('scheduled', 'recurring') and "automation_run"."scheduled_for" is not null and "automation_run"."source_event_id" is null and "automation_run"."source_metric_sample_id" is null) or ("automation_run"."trigger" in ('on_creation', 'manual') and "automation_run"."scheduled_for" is null and "automation_run"."source_event_id" is null and "automation_run"."source_metric_sample_id" is null) or ("automation_run"."trigger" = 'synthetic_event' and "automation_run"."scheduled_for" is null and "automation_run"."source_event_id" is not null and "automation_run"."source_metric_sample_id" is null) or ("automation_run"."trigger" = 'synthetic_condition' and "automation_run"."scheduled_for" is null and "automation_run"."source_event_id" is not null and "automation_run"."source_metric_sample_id" is not null));