import { randomBytes } from "node:crypto";
import {
  existsSync,
  openSync,
  writeFileSync,
  closeSync,
  chmodSync,
} from "node:fs";
import { spawnSync } from "node:child_process";
import { detectContainerRuntime } from "./container-runtime.mjs";

const requiredNodeMajor = 24;
const requiredPnpmVersion = "11.19.0";
const nodeMajor = Number(process.versions.node.split(".")[0]);

if (nodeMajor !== requiredNodeMajor) {
  console.error(
    `Node.js ${requiredNodeMajor} is required; found ${process.version}.`,
  );
  process.exit(1);
}

const pnpm = spawnSync("pnpm", ["--version"], { encoding: "utf8" });
if (pnpm.status !== 0 || pnpm.stdout.trim() !== requiredPnpmVersion) {
  console.error(
    `pnpm ${requiredPnpmVersion} is required. Enable the pinned package manager.`,
  );
  process.exit(1);
}

if (!existsSync(".env.local")) {
  const rootPassword = randomBytes(24).toString("hex");
  const appPassword = randomBytes(24).toString("hex");
  const migrationPassword = randomBytes(24).toString("hex");
  const env = [
    "# Generated by pnpm setup for this local checkout. Never commit this file.",
    "APP_ENV=local",
    "APP_ORIGIN=http://127.0.0.1:3000",
    "DB_NAME=commandry",
    `DB_ROOT_PASSWORD=${rootPassword}`,
    `DB_APP_PASSWORD=${appPassword}`,
    `DB_MIGRATION_PASSWORD=${migrationPassword}`,
    `DATABASE_URL=postgresql://commandry_app:${appPassword}@127.0.0.1:5432/commandry`,
    `DATABASE_MIGRATION_URL=postgresql://commandry_migrate:${migrationPassword}@127.0.0.1:5432/commandry`,
    `BETTER_AUTH_SECRET=${randomBytes(48).toString("base64url")}`,
    `APP_ENCRYPTION_KEY=${randomBytes(48).toString("base64url")}`,
    "INITIAL_ADMIN_EMAIL=",
    "RELEASE_SHA=local",
    "RELEASE_IMAGE_DIGEST=",
    "RELEASE_BUILD_TIME=",
    "DB_POOL_MAX=5",
    "BOSS_POOL_MAX=5",
    "",
  ].join("\n");
  const handle = openSync(".env.local", "wx", 0o600);
  try {
    writeFileSync(handle, env);
  } finally {
    closeSync(handle);
  }
  chmodSync(".env.local", 0o600);
  console.log("Created ignored .env.local with random local-only secrets.");
} else {
  console.log("Using existing .env.local; it was not overwritten.");
}

const installArgs = existsSync("pnpm-lock.yaml")
  ? ["install", "--frozen-lockfile"]
  : ["install"];
const install = spawnSync("pnpm", installArgs, { stdio: "inherit" });
if (install.status !== 0) {
  console.error(
    "Dependency installation failed. Run `pnpm install` after resolving the error.",
  );
  process.exit(install.status || 1);
}

const runtime = detectContainerRuntime();
if (!runtime) {
  console.error(
    "A Docker-compatible Compose runtime is missing. Install a host Compose provider before `pnpm dev` or `pnpm compose:up`.",
  );
  process.exit(1);
}

console.log(
  `Ready: Node ${process.version}, pnpm ${requiredPnpmVersion}, ${runtime.description} (${runtime.version}).`,
);
